### ISSUE TITLE
High CPU Usage on PutFlow2TCP Processor

### ISSUE THREAD

**Issue by jack-broadway** [nerdfunk-net/diode#1]
Hi,

Thank you for the awesome work. I've been using this in my home lab to play with segregated networks with great success!

I've just noticed that the PutFlow2TCP process on NiFi v1.23.2 has very high CPU usage, even when idle. With all my other processors running and PutFlow2TCP disabled, i get a load average of 0.70. With PutFlow2TCP running, i have a load average of 3.50. In both these scenarios, the flows are not processing any data.

My test setup is a basic GetFile -> UpdateAttributes -> PutFlow2TCP | ListenTCP2Flow -> PutFile

This could be from how I'm using it, just wanted to know if this is normal? or if there's anyway i can help diagnose this?

**Comment by nerdfunk-net** [comment]
Hi,

thanks for raising this issue and using the processor. I have (hopefully) found the error. The processor was also triggered idle. I have now deactivated this and tested it on my system. It looks much better now. I hope this does not have any side effects.
I have updated the code for version 1.19.1, 1.23.2, 1.27.0 and 2.0.0M4. I would be pleased if you could test this code and give me some feedback. In Version 2.0.0M4 I have also removed a parameter that was not used. The processor must therefore be configured again. And thanks again for the feedback!

**Comment by jack-broadway** [comment]
Thank you for the quick response! Those commits fixed the issue and CPU usage has returned to normal. Thank you!
